package maintenance

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"
)

// Report is the result of a maintenance pass. It is a derived operational record,
// not a source of truth: the source of truth stays config.yml, the secrets store,
// the Docker runtime, and GitHub webhook registrations.
type Report struct {
	StartedAt      time.Time           `json:"started_at"`
	FinishedAt     time.Time           `json:"finished_at"`
	IaC            IaCResult           `json:"iac"`
	Config         ConfigResult        `json:"config"`
	Caddy          string              `json:"caddy"`
	Certificates   CertResult          `json:"certificates"`
	Webhooks       WebhookResult       `json:"webhooks"`
	Stacks         []StackReport       `json:"stacks"`
	Orphans        []string            `json:"orphans,omitempty"`
	MissingSecrets map[string][]string `json:"missing_secrets,omitempty"`
	Errors         []string            `json:"errors,omitempty"`
}

// IaCResult records the IaC repo pull outcome.
type IaCResult struct {
	Pulled  bool   `json:"pulled"`
	OldHEAD string `json:"old_head,omitempty"`
	NewHEAD string `json:"new_head,omitempty"`
	Error   string `json:"error,omitempty"`
}

// ConfigResult records the config reload outcome.
type ConfigResult struct {
	Loaded bool   `json:"loaded"`
	Error  string `json:"error,omitempty"`
}

// CertResult records TLS certificate health as observed during the pass. Caddy
// owns issuance and renewal; Herald only reports, because a failing renewal is
// otherwise invisible until the certificate dies 30 days later.
type CertResult struct {
	Total        int       `json:"total"`
	Expired      []string  `json:"expired,omitempty"`
	Expiring     []string  `json:"expiring,omitempty"` // valid, but too close to expiry to still be renewing
	NextExpiry   time.Time `json:"next_expiry,omitzero"`
	RenewalError string    `json:"renewal_error,omitempty"`
	Error        string    `json:"error,omitempty"` // could not read Caddy's state
}

// WebhookResult tallies the webhook reconciliation.
type WebhookResult struct {
	Synced  int    `json:"synced"`
	Created int    `json:"created"`
	Pruned  int    `json:"pruned"`
	Errors  int    `json:"errors"`
	Skipped bool   `json:"skipped"` // true when delta mode found no change
	Error   string `json:"error,omitempty"`
}

// StackReport is the per-stack survey result and the action taken.
type StackReport struct {
	Name           string   `json:"name"`
	Source         string   `json:"source"` // "repo" or "path"
	State          string   `json:"state"`  // "running", "stopped", "not deployed"
	Action         string   `json:"action"` // "redeployed", "report", "blocked", "config drift", "none"
	Detail         string   `json:"detail,omitempty"`
	ConfigDrift    bool     `json:"config_drift,omitempty"` // config.yml changed since the last deploy
	MissingSecrets []string `json:"missing_secrets,omitempty"`
}

// addErr appends a top-level error to the report.
func (r *Report) addErr(format string, args ...any) {
	r.Errors = append(r.Errors, fmt.Sprintf(format, args...))
}

// LoadReport reads the last persisted maintenance report from
// <dataDir>/last-sync.json. It returns (nil, nil) when no report exists yet, so a
// fresh server is not treated as an error. The report is a derived read model: its
// liveness fields ("as observed during the last pass") must not be trusted as
// current state — query Docker live for that.
func LoadReport(dataDir string) (*Report, error) {
	path := filepath.Join(dataDir, "last-sync.json")
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading report: %w", err)
	}
	var rep Report
	if err := json.Unmarshal(data, &rep); err != nil {
		return nil, fmt.Errorf("parsing report: %w", err)
	}
	return &rep, nil
}

// Write persists the report to <dataDir>/last-sync.json atomically. It is a read
// model for status/doctor and can be regenerated by re-running a pass.
func (r *Report) Write(dataDir string) error {
	path := filepath.Join(dataDir, "last-sync.json")
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling report: %w", err)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return fmt.Errorf("writing report: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp) //nolint:errcheck
		return fmt.Errorf("renaming report: %w", err)
	}
	return nil
}

func (r *Report) renderCertificates(w io.Writer) {
	c := r.Certificates
	switch {
	case c.Error != "":
		fmt.Fprintf(w, "  Certificates: could not check — %s\n", c.Error)
	case c.Total == 0:
		// Nothing issued yet, or Caddy is down; the Caddy line already says which.
	case len(c.Expired) > 0 || len(c.Expiring) > 0:
		fmt.Fprintf(w, "  Certificates: %d total, %d EXPIRED, %d expiring\n",
			c.Total, len(c.Expired), len(c.Expiring))
		for _, d := range c.Expired {
			fmt.Fprintf(w, "    expired:  %s\n", d)
		}
		for _, d := range c.Expiring {
			fmt.Fprintf(w, "    expiring: %s\n", d)
		}
	default:
		fmt.Fprintf(w, "  Certificates: %d ok, next expiry %s\n",
			c.Total, c.NextExpiry.Local().Format("2006-01-02"))
	}
	if c.RenewalError != "" {
		fmt.Fprintf(w, "  Renewals: FAILING — %s\n", c.RenewalError)
	}
}

// Render writes a human-readable summary of the pass.
func (r *Report) Render(w io.Writer) {
	fmt.Fprintln(w, "Maintenance pass complete:")

	if r.IaC.Error != "" {
		fmt.Fprintf(w, "  IaC pull: error: %s\n", r.IaC.Error)
	} else if r.IaC.Pulled && r.IaC.OldHEAD != r.IaC.NewHEAD {
		fmt.Fprintf(w, "  IaC pull: %s → %s\n", r.IaC.OldHEAD, r.IaC.NewHEAD)
	}

	if r.Config.Error != "" {
		fmt.Fprintf(w, "  Config: INVALID — %s (kept previous config)\n", r.Config.Error)
	} else {
		fmt.Fprintln(w, "  Config: reloaded")
	}

	fmt.Fprintf(w, "  Caddy: %s\n", r.Caddy)
	r.renderCertificates(w)

	switch {
	case r.Webhooks.Error != "":
		fmt.Fprintf(w, "  Webhooks: error: %s\n", r.Webhooks.Error)
	case r.Webhooks.Skipped:
		fmt.Fprintln(w, "  Webhooks: unchanged")
	default:
		fmt.Fprintf(w, "  Webhooks: %d synced, %d created, %d pruned, %d errors\n",
			r.Webhooks.Synced, r.Webhooks.Created, r.Webhooks.Pruned, r.Webhooks.Errors)
	}

	var running, stopped, notDeployed, redeployed int
	for _, s := range r.Stacks {
		switch s.State {
		case "running":
			running++
		case "stopped":
			stopped++
		case "not deployed":
			notDeployed++
		}
		if s.Action == "redeployed" {
			redeployed++
		}
	}
	fmt.Fprintf(w, "  Stacks: %d running, %d stopped, %d not deployed, %d redeployed\n",
		running, stopped, notDeployed, redeployed)

	if len(r.Orphans) > 0 {
		fmt.Fprintf(w, "  Orphans: %d\n", len(r.Orphans))
		for _, o := range r.Orphans {
			fmt.Fprintf(w, "    %s (not in config)\n", o)
		}
	}

	// Pending actions: undeployed stacks (first deploy is manual).
	var pending []string
	for _, s := range r.Stacks {
		if s.State == "not deployed" {
			pending = append(pending, fmt.Sprintf("  → Run 'herald deploy %s' to deploy (not yet deployed)", s.Name))
		}
		if s.Action == "blocked" {
			pending = append(pending, fmt.Sprintf("  → Stack '%s' blocked: missing %v", s.Name, s.MissingSecrets))
		}
		if s.ConfigDrift {
			pending = append(pending, fmt.Sprintf(
				"  → Run 'herald deploy %s': config.yml changed since its last deploy (a domain change needs a redeploy to move the certificate)", s.Name))
		}
	}
	if len(pending) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Pending actions:")
		for _, a := range pending {
			fmt.Fprintln(w, a)
		}
	}

	if len(r.MissingSecrets) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Missing required secrets:")
		for name, keys := range r.MissingSecrets {
			fmt.Fprintf(w, "  stack %q: %v\n", name, keys)
		}
		fmt.Fprintln(w, "Run `herald secret set <key>` to set missing secrets.")
	}

	if len(r.Errors) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "Errors:")
		for _, e := range r.Errors {
			fmt.Fprintf(w, "  %s\n", e)
		}
	}
}
